### ISSUE TITLE
Land's end bug

### ISSUE THREAD

**Issue by LiftedMango** [DylanLange/shayzien-organised-crime#1]
Hey, love the plugin! Not sure if it's still maintained but I figured I'd post just in case. 

When the location is the following, the plugin stops logging locations until it is turned off and on:
We've received reports of a gang meeting in a house in Land's End. | The house north of the bank in Land's End.

I've tried it with setting multi zones only but hasn't helped. 

Happy to provide more info if needed

**Comment by DylanLange** [comment]
Thank you for reporting! Sorry I'm a bit late to the party here. I'll take a look at this when addressing #2

**Comment by LiftedMango** [comment]
Awesome! cool to see your still on it :D

**Comment by DylanLange** [comment]
Should be fixed with https://github.com/runelite/plugin-hub/pull/1642 being merged in
