### ISSUE TITLE
not showing any data

### ISSUE THREAD

**Issue by Dinouh** [DylanLange/shayzien-organised-crime#2]
hey idk if im doing anyhthing wrong.
i installed the plugin and enabled it. when i read multiple gang meeting info it doesnt show anything in the plugin.

what could be the problem?

**Comment by DylanLange** [comment]
Hey @Dinouh thanks for asking. I've been pinged about this privately as well. I think that it has to do with the Shayzien rework that happened recently. The plugin won't be up to date with the latest set of locations that are possible to run in to.

I'll do my best to get a fix in some time in the next week. Thanks

**Comment by DylanLange** [comment]
Should be fixed with https://github.com/runelite/plugin-hub/pull/1642 being merged in
