### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by qpalzm1247** [DylanLange/shayzien-organised-crime#6]
remove this useless thing out of the 3 spots i got only 1 worked being the cow paddock. the other 2 locations i could not get posted. really annoying and frustrating.

**Comment by qpalzm1247** [comment]
looking at previous the ruins broke it for me. reinstalling didn't not fix it.

**Comment by DylanLange** [comment]
Please provide specific details of which areas didn't work so that I can make updates. I.e. a screenshot of the billboard, and the exact text if you can get access to that.

I'm not playing OSRS anymore, but happy to accept PRs that updates this, or alternatively hand over ownership of this repo to somebody who is able to maintain it

**Comment by Mordo95** [comment]
I did invite you to my refreshment of the plugin is why you got here. Why not just accept that one?

**Comment by DylanLange** [comment]
> I did invite you to my refreshment of the plugin is why you got here. Why not just accept that one?

I can see you [forked it](https://github.com/DylanLange/shayzien-organised-crime/compare/master...Mordo95:shayzien-organised-crime:master) and added a commit, but you haven't submitted a pull request to merge it in.

If you'd like, I can just transfer ownership of this repository to you. Just let me know.

**Comment by Mordo95** [comment]
> > I did invite you to my refreshment of the plugin is why you got here. Why not just accept that one?
> 
> I can see you [forked it](https://github.com/DylanLange/shayzien-organised-crime/compare/master...Mordo95:shayzien-organised-crime:master) and added a commit, but you haven't submitted a pull request to merge it in.
> 
> If you'd like, I can just transfer ownership of this repository to you. Just let me know.

Sure. I'm having more ideas for features anyways and I'm active every day on osrs.
I copied the repo earlier but Runelite didn't agree with that. So had to fork it.

**Comment by DylanLange** [comment]
> Sure. I'm having more ideas for features anyways and I'm active every day on osrs. I copied the repo earlier but Runelite didn't agree with that. So had to fork it.

Please remove your repository so i can transfer ownership to you. there's a naming conflict currently. you could rename yours i guess? up so you
